//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Car
    {
        public int Id { get; set; }

        [StringLength(60, MinimumLength = 2)]
        [Required]
        public string Model { get; set; }

        [StringLength(60, MinimumLength = 2)]
        [Required]
        public string Make { get; set; }

        [Range(1500, 3000)]
        public Nullable<int> Year { get; set; }

        [StringLength(60, MinimumLength = 2)]
        [Required]
        public string Engine { get; set; }

        
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }


        public string Picture { get; set; }
    }
}
